services:
  db:
    image: postgres:16-alpine
    container_name: music_classroom_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: music_classroom
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: music_classroom_app
    depends_on:
      - db
    environment:
      NODE_ENV: development
      TZ: Europe/Paris
      DATABASE_URL: postgresql://app:app@db:5432/music_classroom?schema=public
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "sleep 5 && npx prisma db push && node src/jobs/scraper.js"

volumes:
  db_data:
