services:
  db:
    image: postgres:16-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: music_classroom_app
    depends_on:
      - db
    environment:
      NODE_ENV: development
      TZ: Europe/Paris
      DATABASE_URL: postgresql://app:app@db:5432/music_classroom?schema=public
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "npx prisma db push && node src/app.js && node src/jobs/scraper.js"

volumes:
  db_data:
